# These are supported funding model platforms

github: [Shadman-2021]
patreon: patreon_username
open_collective: open_collective_username
ko_fi: ko_fi_username
tidelift: tidelift_platform-name/package-name
community_bridge: community_bridge_project-name
liberapay: liberapay_username
issuehunt: issuehunt_username
otechie: otechie_username
lfx_crowdfunding: lfx_crowdfunding_project-name
custom: ['custom_link1', 'custom_link2']
